# Generated by Django 2.0.4 on 2018-04-25 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30)),
                ('parent_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Node')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Tree'),
        ),
    ]
