# Generated by Django 2.0.4 on 2018-04-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20180425_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='tree',
            new_name='manga',
        ),
    ]
