# Generated by Django 2.0.4 on 2018-04-25 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20180425_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='manga',
            field=models.ForeignKey(default='first_menu', on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
        ),
    ]
