# Generated by Django 2.0.4 on 2018-04-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20180425_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='manga',
            new_name='menu',
        ),
    ]
